name: v_chat_voice_player
description: v chat voice player package this item is part of v_chat_sdk and it can be used as a standalone package
version: 3.1.0
homepage: https://v-chat-sdk.github.io/vchat-v2-docs/docs/intro
issue_tracker: https://github.com/v-chat-sdk/v_chat_voice_player/issues
repository: https://github.com/v-chat-sdk/v_chat_voice_player

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  meta: ^1.16.0
  flutter_vlc_player: ^7.4.3
  path: ^1.9.0
  audio_waveforms: ^1.3.0
  audioplayers: ^6.5.0
  v_platform: ^2.1.4
  intl: ^0.20.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux:
